output "application_url" { value = module.edge.application_url }
output "eks_cluster_name" { value = module.kubernetes.cluster_name }
output "document_bucket" { value = module.documents.bucket_id }
output "document_kms_key_arn" { value = module.documents.kms_key_arn }
output "vpc_id" { value = module.vpc.vpc_id }
output "public_subnet_cidrs" { value = var.public_subnet_cidrs }
output "private_subnet_cidrs" { value = var.private_subnet_cidrs }
output "telemetry_bucket" { value = module.telemetry.bucket_id }
output "ingestion_queue_url" { value = module.queues.queue_url }
output "ingestion_dlq_url" { value = module.queues.dlq_url }
output "ecr_repository_urls" { value = module.ecr.repository_urls }
output "aurora_endpoint" { value = module.database.cluster_endpoint }
output "aurora_master_secret_arn" {
  value     = module.database.master_user_secret_arn
  sensitive = true
}
output "cognito_user_pool_id" { value = module.iam.cognito_user_pool_id }
output "cognito_client_id" { value = module.iam.cognito_client_id }
output "cognito_domain" { value = module.iam.cognito_domain }
output "cognito_authorize_url" { value = module.iam.cognito_authorize_url }
output "cognito_token_url" { value = module.iam.cognito_token_url }
output "cognito_logout_url" { value = module.iam.cognito_logout_url }
output "runtime_secret_arn" { value = module.iam.runtime_secret_arn }
output "drift_role_arn" { value = module.iam.drift_role_arn }
output "ecr_publisher_role_arn" { value = module.iam.ecr_publisher_role_arn }
output "sns_topic_arn" { value = module.monitoring.sns_topic_arn }
output "alb_target_group_arn" { value = module.edge.target_group_arn }
output "application_deploy_project_name" { value = module.deployment.project_name }
output "application_deploy_role_arn" { value = module.deployment.trigger_role_arn }
output "duckdns_ipv4" { value = module.edge.duckdns_ipv4 }
output "global_accelerator_ipv4_addresses" { value = module.edge.global_accelerator_ipv4_addresses }
