"""describe change

Revision ID: 876befa85d63
Revises: 20260823_0001
Create Date: 2026-08-27 06:41:18.412891
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '876befa85d63'
down_revision: Union[str, None] = '20260823_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
