from __future__ import annotations

import json
import logging
import threading
from collections.abc import Iterator
from contextlib import contextmanager
from contextvars import ContextVar, Token
from datetime import UTC, datetime
from time import perf_counter
from typing import Any

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.sdk.trace.sampling import ParentBased, TraceIdRatioBased
from opentelemetry.trace import Status, StatusCode
from prometheus_client import Counter, Gauge, Histogram, start_http_server

from rag_platform.config import ObservabilitySettings

request_id_var: ContextVar[str | None] = ContextVar("request_id", default=None)
tenant_id_var: ContextVar[str | None] = ContextVar("tenant_id", default=None)
service_var: ContextVar[str] = ContextVar("service", default="rag-platform")

HTTP_REQUESTS = Counter(
    "rag_http_requests_total", "Completed HTTP requests", ["service", "method", "route", "status"]
)
HTTP_DURATION = Histogram(
    "rag_http_request_duration_seconds",
    "HTTP request latency",
    ["service", "method", "route"],
    buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120),
)
RAG_QUERIES = Counter("rag_queries_total", "RAG queries", ["service", "outcome"])
RAG_STAGE_DURATION = Histogram(
    "rag_stage_duration_seconds",
    "RAG pipeline stage latency",
    ["service", "stage"],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120),
)
RAG_CITATIONS = Histogram(
    "rag_citations_per_answer",
    "Citations returned per answer",
    ["service"],
    buckets=(0, 1, 2, 3, 5, 8, 13, 21),
)
RAG_GENERATED_TOKENS = Counter(
    "rag_generated_tokens_total", "Tokens generated by the language model", ["service", "model"]
)
RAG_GENERATION_TOKENS_PER_SECOND = Gauge(
    "rag_generation_tokens_per_second",
    "Most recently observed language-model generation throughput",
    ["service", "model"],
)
APPLICATION_ERRORS = Counter(
    "rag_application_errors_total", "Application errors", ["service", "component", "error_type"]
)
INGESTION_DOCUMENTS = Counter(
    "rag_ingestion_documents_total", "Documents processed by ingestion", ["service", "outcome"]
)
DRIVE_SYNC_RUNS = Counter(
    "rag_drive_sync_runs_total", "Google Drive synchronization runs", ["service", "outcome"]
)
DRIVE_SYNC_LAST_SUCCESS = Gauge(
    "rag_drive_sync_last_success_unixtime",
    "Unix timestamp of the last successful Drive synchronization",
    ["service"],
)

_configuration_lock = threading.Lock()
_tracing_configured = False
_metrics_servers: set[tuple[str, int]] = set()


def _trace_id() -> str | None:
    span_context = trace.get_current_span().get_span_context()
    if not span_context.is_valid:
        return None
    return f"{span_context.trace_id:032x}"


class StructuredJsonFormatter(logging.Formatter):
    """Stable JSON schema that excludes raw request and document content."""

    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, Any] = {
            "timestamp": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
            "level": record.levelname,
            "service": getattr(record, "service", None) or service_var.get(),
            "request_id": getattr(record, "request_id", None) or request_id_var.get(),
            "tenant_id": getattr(record, "tenant_id", None) or tenant_id_var.get(),
            "trace_id": getattr(record, "trace_id", None) or _trace_id(),
            "message": record.getMessage(),
        }
        for key in ("component", "operation", "status", "latency_ms", "document_id", "job_id"):
            value = getattr(record, key, None)
            if value is not None:
                payload[key] = value
        if record.exc_info:
            payload["error_type"] = record.exc_info[0].__name__
        return json.dumps(payload, separators=(",", ":"), ensure_ascii=False)


def configure_observability(config: ObservabilitySettings, service: str) -> None:
    service_var.set(service)
    root = logging.getLogger()
    root.setLevel(config.log_level.upper())
    if config.enabled:
        handler = logging.StreamHandler()
        handler.setFormatter(StructuredJsonFormatter())
        root.handlers[:] = [handler]

    global _tracing_configured
    with _configuration_lock:
        if config.enabled and not _tracing_configured:
            provider = TracerProvider(
                resource=Resource.create({SERVICE_NAME: service}),
                sampler=ParentBased(TraceIdRatioBased(config.trace_sample_ratio)),
            )
            provider.add_span_processor(
                BatchSpanProcessor(OTLPSpanExporter(endpoint=config.otlp_traces_endpoint))
            )
            trace.set_tracer_provider(provider)
            _tracing_configured = True
        address = (config.metrics_host, config.metrics_port)
        if config.enabled and address not in _metrics_servers:
            start_http_server(config.metrics_port, addr=config.metrics_host)
            _metrics_servers.add(address)


def set_request_id(value: str | None) -> Token[str | None]:
    return request_id_var.set(value)


def set_tenant_id(value: str | None) -> Token[str | None]:
    return tenant_id_var.set(value)


def reset_request_id(token: Token[str | None]) -> None:
    request_id_var.reset(token)


def reset_tenant_id(token: Token[str | None]) -> None:
    tenant_id_var.reset(token)


def tracer(name: str):
    return trace.get_tracer(name)


@contextmanager
def observe_stage(stage: str, **attributes: str | int | float | bool) -> Iterator[None]:
    started = perf_counter()
    with tracer("rag-platform").start_as_current_span(stage) as span:
        for key, value in attributes.items():
            span.set_attribute(key, value)
        try:
            yield
        except Exception as exc:
            span.record_exception(exc)
            span.set_status(Status(StatusCode.ERROR))
            raise
        finally:
            RAG_STAGE_DURATION.labels(service_var.get(), stage).observe(perf_counter() - started)
