from __future__ import annotations

from enum import StrEnum


class DocumentStatus(StrEnum):
    RECEIVED = "RECEIVED"
    DOWNLOADING = "DOWNLOADING"
    PARSING = "PARSING"
    CHUNKING = "CHUNKING"
    EMBEDDING = "EMBEDDING"
    INDEXING = "INDEXING"
    VALIDATING = "VALIDATING"
    ACTIVE = "ACTIVE"
    FAILED_DOWNLOAD = "FAILED_DOWNLOAD"
    FAILED_PARSE = "FAILED_PARSE"
    FAILED_EMBEDDING = "FAILED_EMBEDDING"
    FAILED_INDEXING = "FAILED_INDEXING"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    DELETING = "DELETING"
    DELETED = "DELETED"


class IssueSeverity(StrEnum):
    WARNING = "WARNING"
    ERROR = "ERROR"


class IssueCode(StrEnum):
    NOT_FOUND = "NOT_FOUND"
    NOT_A_FILE = "NOT_A_FILE"
    NOT_PDF = "NOT_PDF"
    CORRUPTED_PDF = "CORRUPTED_PDF"
    # This is a validation issue identifier, not a password or credential.
    PASSWORD_PROTECTED = "PASSWORD_PROTECTED"  # nosec B105
    EMPTY_PDF = "EMPTY_PDF"
    ZERO_EXTRACTED_TEXT = "ZERO_EXTRACTED_TEXT"
    LOW_TEXT_DENSITY = "LOW_TEXT_DENSITY"
    DUPLICATE_DOCUMENT = "DUPLICATE_DOCUMENT"
    EXCESSIVE_PAGE_COUNT = "EXCESSIVE_PAGE_COUNT"
    UNSUPPORTED_ENCODING = "UNSUPPORTED_ENCODING"
    EXTRACTION_ERROR = "EXTRACTION_ERROR"
