import { api } from "@/lib/api";

type Detail={document:any;versions:any[];permissions:any[];ingestion_jobs:any[]};
const stages=["PARSING","CHUNKING","EMBEDDING","INDEXING","VALIDATING"];
export default async function DocumentDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params; let data:Detail|null=null; try{data=await api<Detail>(`/api/v1/documents/${id}`)}catch{}
  if(!data)return <div className="card">Document unavailable.</div>; const d=data.document; const v=data.versions[0]; const job=data.ingestion_jobs[0];
  return <><header className="header"><div><div className="eyebrow">Document detail</div><h1>{d.filename}</h1><p>{d.id}</p></div><div className="actions"><button className="secondary">Reindex</button><button>Delete</button></div></header><div className="grid two"><section className="card"><h2>Metadata</h2><table><tbody><tr><td>Status</td><td><span className="badge">{d.status}</span></td></tr><tr><td>Source</td><td>{d.source}</td></tr><tr><td>Version</td><td>{v?.version_number??"—"}</td></tr><tr><td>Checksum</td><td>{v?.checksum_sha256?.slice(0,18)}…</td></tr><tr><td>Size</td><td>{v?.file_size_bytes?.toLocaleString()} bytes</td></tr><tr><td>Pages / chunks</td><td>{v?.page_count??0} / {v?.chunk_count??0}</td></tr><tr><td>Embedding</td><td>{v?.embedding_version??"Pending"}</td></tr></tbody></table></section><section className="card"><h2>Ingestion state</h2><p>{job?.status??"No active job"}</p><div className="pipeline">{stages.map((stage,i)=>{const active=job?.stage===stage;const done=stages.indexOf(job?.stage)>i||d.status==="ACTIVE";const value=done?100:active?job.progress_percent:0;return <div className="stage" key={stage}><b>{stage}</b><div className="bar"><i style={{width:`${value}%`}}/></div><span>{done?"✓":active?`${value}%`:"pending"}</span></div>})}</div></section><section className="card"><h2>Permissions</h2>{data.permissions.map(p=><p key={p.id}>{p.principal_type}: {p.principal_id} · {p.capability}</p>)}</section><section className="card"><h2>Activity</h2><p>Created {new Date(d.created_at).toLocaleString()}</p><p>Updated {new Date(d.updated_at).toLocaleString()}</p></section></div></>;
}
